stages:
  - build

build_job:
  stage: build
  image: "debian:stretch"
  before_script:
    - apt-get -y install python3 python3-venv python3-dev # Make sure Python3 is installed
    - apt-get -y install nginx
  script:
    - python3 -m venv dist_root/srv/jodlgang/jodlenv
    - dist_root/srv/jodlgang/jodlenv/bin/pip install -r requirements.txt
  artifacts:
    paths:
      - metadata.yml
      - dist_root/
  only:
    - master
  tags:
    - faust
    - docker