stages:
  - build

build_job:
  stage: build
  image: "debian:stretch"
  before_script:
    - apt-get -y install python3 python3-venv python3-dev # Make sure Python3 is installed
    - apt-get -y install nginx
  script:
    - mkdir -p dist_root/srv/jodlgang
    - python3 -m venv dist_root/srv/jodlgang/jodlenv
    - source dist_root/srv/jodlgang/jodlenv/bin/activate
    - cp requirements.txt dist_root/srv/jodlgang/
    - dist_root/srv/jodlgang/jodlenv/bin/pip install -r requirements.txt
