stages:
  - build
  - upload

build_job:
  stage: build
  image: "debian:stretch"
  before_script:
    - mkdir -p "$CI_PROJECT_DIR/.apt" "$CI_PROJECT_DIR/.pip"
    - echo 'deb http://ftp.debian.org/debian stretch-backports main' >> /etc/apt/sources.list
    - apt -o dir::cache="$CI_PROJECT_DIR/.apt" -yqq update
    - apt -o dir::cache="$CI_PROJECT_DIR/.apt" -yqq install python3 python3-venv python3-dev build-essential rsync
  cache:
    paths:
      - .apt/
      - .pip/
  script:
    - python3 -m venv dist_root/srv/jodlgang/jodlenv # Set up virtual environment
    - dist_root/srv/jodlgang/jodlenv/bin/pip install wheel # Install wheel before the other requirements
    - dist_root/srv/jodlgang/jodlenv/bin/pip install -r requirements.txt # Install python libraries
    - dist_root/srv/jodlgang/jodlenv/bin/python src/jodlgang/manage.py collectstatic --no-input # Let Django collect its static files
    - cp webserver/nginx/jodlgang_nginx.conf dist_root/srv/jodlgang/ # Copy nginx configuration
    - cp webserver/uwsgi/jodlgang_uwsgi.ini dist_root/srv/jodlgang/ # Copy uwsgi configuration
    - rsync -av src/jodlgang dist_root/srv/jodlgang/ --exclude "__pycache__" --exclude "migrations" --exclude "*.h5" # Copy django files
  artifacts:
    paths:
      - metadata.yml
      - dist_root/
  only:
    - master
  tags:
    - faust
    - docker

upload_job:
  stage: upload
  script:
    - ssh ci-upload@www.faust.cs.fau.de mkdir -p "/var/www/files/internal/ci/faustctf/2018/$CI_PROJECT_NAME"
    - tar -v -czp -H posix -f dist_root.tar.gz -C dist_root .
    - scp metadata.yml dist_root.tar.gz "ci-upload@www.faust.cs.fau.de:/var/www/files/internal/ci/faustctf/2018/$CI_PROJECT_NAME/"
  after_script:
    - find "$CI_PROJECT_DIR" -mindepth 1 -delete
  variables:
    GIT_STRATEGY: none
  only:
    - master
  tags:
    - faust
    - www-upload