# Generated by Django 2.0.1 on 2018-05-06 04:09

from django.db import migrations
import string
import random
import json


def replace_umlauts(input):
    return input.replace("ä", "ae").replace("ö", "oe").replace("ü", "ue").replace("Ä", "Ae").replace("Ö", "oe").replace("Ü", "ue").replace("ß", "ss")


def random_password(n=64):
    return "".join(random.choice(string.ascii_uppercase + string.digits) for _ in range(n))


def create_user_database(apps, schema_editor):
    # TODO make sure this file is not included on the vulnbox!!!
    user_names_file = "/media/explicat/Moosilauke/ctf/facescrub/training/class_label_mapping_names.json"
    with open(user_names_file, "r") as f:
        user_names = json.load(f)

    User = apps.get_model('jodlplatform', 'User')
    for i, name in enumerate(user_names):
        first_name = replace_umlauts(name.split(" ", 1)[0]).lower()
        last_name = replace_umlauts(name.split(" ", 1)[1]).replace(" ", ".").lower()
        email = first_name + "." + last_name + "@jodlgang.com"
        password = random_password()
        User(id=i, name=name, email=email, password=password).save()


class Migration(migrations.Migration):

    dependencies = [
        ('jodlplatform', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_database)
    ]
